name: build
on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
    steps:
      - name: Environment
        run: env | sort
      - uses: actions/checkout@v4

      - name: generate p12
        run: |
          openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj /CN=MyHost.com
          openssl pkcs12 -export -in cert.pem -inkey key.pem -out certificado.p12 -name "Alias of cert" -passout pass:"checknif" -passin pass:""

      - name: Set up JDK 21 for x64
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: ./gradlew nativeCompile -P CHECKNIF_CERTIFICADO=certificado.p12 -P CHECKNIF_PASSWORD=checknif