name: build
on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
    steps:
      - name: Environment
        run: env | sort
      - uses: actions/checkout@v4

      - name: save p12 to file
        run: |
          echo -n $P12 | base64 -d > ./certificado.p12
        env:
          P12: ${{ secrets.P12 }}

      - name: Set up JDK 21 for x64
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: ./gradlew buildNative -P CHECKNIF_CERTIFICADO=certificado.p12 -P CHECKNIF_PASSWORD=$P12_PWD
        env:
          P12_PWD: ${{ secrets.P12_PWD }}

