name: release
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env | sort
      - uses: actions/checkout@v4

      - name: save p12 to file
        run: |
          echo -n $P12 | base64 -d > ./certificado.p12
        env:
          P12: ${{ secrets.P12 }}

      - name: Set up JDK 21 for x64
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: ./gradlew nativeCompile -P CHECKNIF_CERTIFICADO=certificado.p12 -P CHECKNIF_PASSWORD=$P12_PWD
        env:
          P12_PWD: ${{ secrets.P12_PWD }}

      - name: version
        run: echo "::set-output name=version::$(./gradlew properties -q | awk '/^version:/ {print $2}')"
        id: version

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/native/nativeCompile/checknif
          asset_name: checknif
          asset_content_type: binary/octet-stream
